[package]
name = "mrpm"
version = "0.4.1"
edition = "2024"
authors = ["zekroTJA <riho@live.de>"]
description = "A Modrinth plugin/package manager"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.12.15", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
serde_json = "1.0.140"
inquire = "0.7.5"
toml = "0.8.21"
yansi = "1.0.1"
loose-semver = { version = "1.1.0" , features = ["serde-nofail"] }

[profile.release]
strip = true
opt-level = "s"
codegen-units = 1
lto = true
panic = "unwind"
